root: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier

rules:
  ###########
  # PLUGINS #
  ###########

  ###########
  # BUILTIN #
  ###########
  no-param-reassign: off
  no-underscore-dangle: off

  ###########
  # SPECIAL #
  ###########
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: false
